// import "./style.css";
// import "./02_string_number_dom/string.ts";
// import "./02_string_number_dom/number.ts";
// import "./02_string_number_dom/dom.ts";
// import "./02_exercises/string.ts";
// import "./02_exercises/number.ts";
// import "./02_exercises/bonus.ts";
// import "./03_conditionals_math_date/math.ts";
// import "./03_conditionals_math_date/conditionals.ts";
// import "./03_conditionals_math_date/date.ts";
// import "./03_exercises/conditionals.ts";
// import "./03_exercises/date.ts";
// import "./03_exercises/math.ts";
import "./04_functions/functions.ts";
import "./04_functions/scope.ts";
import "./04_exercises/functions.ts";
import "./04_exercises/basketball.ts";
import "./05_arrays/array.ts";
import "./05_exercises/array_exercise.ts";
import "./05_exercises/array_bonus.ts";
import "./06_arrays/array.ts";
import "./06_arrays/sort.ts";
import " ./";
